services:
  postgres:
    image: postgres:15-alpine
    container_name: practice_db
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dsr_practice_db
    ports:
      - "25434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynet
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
        - mynet
    depends_on:
      - backend

networks:
  mynet:
    driver: bridge